title: "Bijoychandra Takhellambam"
author: "Bijoychandra S. Takhellambam"
description: "University of Maryland"
url: "https://bijoychandraAU.github.io"
baseurl: ""                          # "" if at root, "/reponame" if in a subfolder
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

show_excerpts: true
show_frame: true
show_sidebar: false
minimal: true

navigation:
  - {file: "index.md",    title: "Home"}
  - {file: "Research.md", title: "Research & Service"}
  - {file: "Teaching.md", title: "Teaching & Mentoring"}
  - {file: "awards.md",   title: "Honors & Awards"}
  - {url: "/File/Bijoychandra_CV.pdf", title: "CV"}

external:
  - {title: Mail,          icon: "fas fa-envelope",    url: "mailto:bijoytbl@umd.edu"}
  - {title: Github,        icon: "fab fa-github",      url: "https://github.com/bijoychandraAU"}
  - {title: Linkedin,      icon: "fab fa-linkedin",    url: "https://www.linkedin.com/in/bijoychandra/"}
  - {title: Google Scholar,icon: "fas fa-graduation-cap", url: "https://scholar.google.com/citations?user=I6bZieUAAAAJ&hl=en"}

plugins:
  - jekyll-feed
  - jekyll-seo-tag
